import { Ad, Coupon } from '@/types';

// Mock de dados para desenvolvimento

export const mockAds: Ad[] = [
  {
    id: '1',
    companyId: '2',
    companyName: 'Tech Solutions',
    title: 'Desconto de 20% em Serviços de TI',
    description: 'Aproveite nosso desconto especial em serviços de consultoria e desenvolvimento de software.',
    imageUrl: 'https://via.placeholder.com/400x300/1e3a5f/ffffff?text=Tech+Solutions',
    bannerUrl: 'https://via.placeholder.com/800x200/1e3a5f/ffffff?text=Banner+Promocional',
    couponCode: 'TECH20',
    discount: 20,
    status: 'active',
    views: 1250,
    clicks: 340,
    couponsRedeemed: 89,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    companyId: '2',
    companyName: 'Marketing Pro',
    title: '15% OFF em Campanhas Digitais',
    description: 'Crie campanhas impactantes com nosso desconto exclusivo para novos clientes.',
    imageUrl: 'https://via.placeholder.com/400x300/334155/ffffff?text=Marketing+Pro',
    bannerUrl: 'https://via.placeholder.com/800x200/334155/ffffff?text=Banner+Marketing',
    couponCode: 'MARKET15',
    discount: 15,
    status: 'active',
    views: 890,
    clicks: 210,
    couponsRedeemed: 45,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    companyId: '2',
    companyName: 'Design Studio',
    title: '30% OFF em Identidade Visual',
    description: 'Transforme sua marca com um design profissional e moderno.',
    imageUrl: 'https://via.placeholder.com/400x300/3b82f6/ffffff?text=Design+Studio',
    bannerUrl: 'https://via.placeholder.com/800x200/3b82f6/ffffff?text=Banner+Design',
    couponCode: 'DESIGN30',
    discount: 30,
    status: 'active',
    views: 2100,
    clicks: 567,
    couponsRedeemed: 123,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockCoupons: Coupon[] = [
  {
    id: '1',
    adId: '1',
    userId: '1',
    code: 'TECH20',
    discount: 20,
    status: 'active',
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    adId: '2',
    userId: '1',
    code: 'MARKET15',
    discount: 15,
    status: 'used',
    redeemedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
